---
#
# Ansible managed
#
repository:
  description: Install and configure Metricbeat, manage Metricbeat modules.
  homepage: https://buluma.github.io/
  topics: metricbeat, ansible, molecule, tox, playbook
