---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-metricbeat
      metricbeat_elasticsearch_password: "My-P@s5w0rd."
      metricbeat_modules:
        - name: system
          state: enabled
